name: Video Processing Pipeline

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'YouTube Video URL'
        required: true
        type: string
      segment_duration:
        description: 'Segment duration in minutes'
        required: false
        default: '20'
        type: string

jobs:
  process-video:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install youtube-dl moviepy openai-whisper pandas

    - name: Create directories
      run: |
        mkdir -p output/videos
        mkdir -p output/transcripts
        mkdir -p output/index

    - name: Process video
      run: |
        echo "Starting video processing..."
        python scripts/process_video.py "${{ github.event.inputs.video_url }}" "${{ github.event.inputs.segment_duration }}"
        echo "Processing complete"
        
    - name: List generated files
      run: |
        echo "Output files:"
        ls -R output/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: processed-video-files
        path: output/
        retention-days: 5
